package by.gsu.epamlab.controllers;

public class ConstantsJsp {
    public static final String LOGIN = "login";
    public static final String PASSWORD = "password";
    public static final String MAIL = "mail";
    public static final String ID_USER = "idUser";
    public static final String TYPE_TABLE = "nameTable";
    public static final String REFERER = "referer";
    public static final String LIST_TASKS = "list";
    public static final String USER_PARAM = "user";
    public static final String NAME_FILTER = "URLFilter";
    public static final String LOGIN_FILTER = "LoginFilter";
    public static final String ADD_TASK_VALUE = "task";
    public static final String ADD_TASK_DATE = "date";
    public static final String NAMES_TYPE_TABLES = "namesTable";
    public static final String BUTTONS_OPERATIONS = "buttons";
    public static final String ID_TASK_FOR_OPERATION = "idTask";
    public static final String PRESSED_BUTTON = "button";
    public static final String REG_PATH = ".*/";
    public static final String DEL = "";
    public static final String START_URL = "/start";
    public static final String MAIN_URL = "/main";
    public static final String LOGIN_URL = "/login";
    public static final String REGISTRATION_URL = "/registration";
    public static final String LOGOUT_URL = "/logout";
    public static final String OPERATIONS_URL = "/operations";
    public static final String ADD_URL = "/add";
    public static final String ADD_TASK_JSP = "/addTask.jsp";
    public static final String KEY_PROPS_NAME = "propsName";
    public static final String WEB_DATA = "factory.web.data";
    public static final String WEB_TASK = "factory.web.task";
    public static final String PROPERTIES_VALUE_RESOURCES_CONFS = "resources.web";
    public static final String DB_NAME = "db.name";
    public static final String DB_USER = "db.user";
    public static final String DB_PASSWORD = "db.password";
    public static final String PAGE_LOGIN_IN_JSP = "/loginIn.jsp";
    public static final String PAGE_REG_JSP = "/registrate.jsp";
    public static final String PAGE_MAIN_JSP = "/main.jsp";
    public static final String PAGE_ERR_CODE = "/errorCode.jsp";
    public static final String PAGE_ERR_EXCEPTION = "/errorException.jsp";
    public static final String PAGE_INDEX_JSP = "/index.jsp";
    public static final String CON_MAIN = "/main?nameTable=Today";
    public static final String CON_MAIN_HADING = "/main?nameTable=";
    public static final String ATT_ERR_MESSAGE = "errorMessage";
    public static final String ERR_MESSAGE = "Invalid Login or Password";
    public static final String ERR_DB = "Problem with database...";
    public static final String ERR_DB_CON_PROP = "Database error... Invalid input file...";
    public static final String ERR_USER = "This user has already been registered...";
    public static final String ERR_POST = "method POST post is wrong for command: ";
    public static final String ERR_GET = "method GET post is wrong for command: ";
    public static final int COLUMN_INDEX_FIRST = 1;
    public static final int COLUMN_INDEX_SECOND = 2;
    public static final int COLUMN_INDEX_THIRD = 3;
}